openapi: 3.0.0

info:
  title: Pump-API-Example
  description: This is a REST API to control a directly connected dosing pump
    
    ----
    
    Using this API you can run and retrieve pump_water operations
  contact:
    name: Rodrigo Moreno Garcia
    email: rodr@itu.dk
  version: 0.1.0

servers:
  - url: ''
    variables:
      protocol:
        default: http
        enum:
          - http
          
          
paths:
  /pump_water/params:
    
    get:
      tags:
        - Pump
      summary: return pump parameters
      description: return pump information and available parameter values
      responses:
        '200':
          description: The pump parameters object in JSON format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pump_water_operation_params'
                
  /pump_water:
  
    get:
      tags:
        - Pump
      summary: return all operations
      description: return all operations that have been run on the device
      responses:
        '200':
          description: An array of all operations in JSON format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pump_water_operations_data'
  
    post:
      tags:
        - Pump
      summary: run pump_water operation
      description: run the pump_water operation by providing parameter values 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pump_water_operation'
      responses:
        '201':
          description: The operation has been run succesfully and the measures have been taken
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pump_water_operation_data'
                
                
    
                
components:
  schemas:
  
    Pump_water_operations_data:
      description: An array of historical pump water operations and data
      type: array
      items:
        $ref: '#/components/schemas/Pump_water_operation_data'
      example:
        - id: 1
          meta_data:
            id: 1
            type: "pump_water"
            pumping_time: 20
            pumping_speed: 100
            input_substances: 
              - "Water"
            measure: 
              - type: "temp"
                measure_time: "at_end"
          data:
            - type: temp
              measured_data: 21.5
        - id: 2
          meta_data:
            id: 2
            type: "pump_water"
            pumping_time: 50
            pumping_speed: 200
            input_substances: 
              - "Water"
            measure: 
              - type: "temp"
                measure_time: "at_start"
          data:
            - type: temp
              measured_data: 19.7
              
              
    Pump_water_operation:
      type: object
      properties:
        id:
          type: string
          description: 'The pump id'
        type:
          type: string
          description: The operation type
        pumping_time: 
          type: number
          minimum: 0
          maximum: 500
          description: The time the pump will be on
        pumping_speed:
          type: number
          minimum: 0
          maximum: 255
          description: The speed of the pump (in terms of PWM output)
        input_substances:
          type: array
          items:
            type: string
          description: The selected input substances for the operation
        measure:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
                description: The type of measurement performed
              measure_time: 
                type: string
                description: The time of measure
      example:
        id: 1
        type: "pump_water"
        pumping_time: 20
        pumping_speed: 100
        input_substances: 
          - "Water"
        measure: 
          - type: "temp"
            measure_time: "at_end"
        
    Pump_water_operation_params:
      type: object
      properties:
        id:
          type: string
          description: Generic pump id
        type:
          type: string
          description: The operation type
        pumping_time: 
          type: array
          items:
            type: number
          minItems: 2
          maxItems: 2
          description: The pumping time min and max values in seconds
        pumping_speed:
          type: array
          items:
            type: number
          minItems: 2
          maxItems: 2
          description: The pumping speed min and max values in PWM values
        input_substances:
          type: array
          items:
            type: string
          description: The available input substances for the operation
        measure:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
                description: One type of available measurement
              measure_time: 
                type: string
                description: Available times for measure
      example:
        id: 0
        type: "pump_water"
        pumping_time: 
          - 0
          - 50
        pumping_speed: 
          - 0
          - 255
        input_substances: 
          - "Water"
        measure: 
          - type: "temp"
            measure_time: 
              - "at_start"
              - "at_end"
        
        
    Pump_water_operation_data:
      type: object
      properties:
        id:
          type: string
          description: The pump id
        meta_data: 
          $ref: '#/components/schemas/Pump_water_operation'
        data: 
          type: array
          items:
            type: object
            properties:
              type:
                type: string
                description: The type of measurement performed
              measured_data:
                type: number
                description: The measured value
      example:
        id: 1
        meta_data:
          id: 1
          type: "pump_water"
          pumping_time: 20
          pumping_speed: 100
          input_substances: 
            - "Water"
          measure: 
            - type: "temp"
              measure_time: "at_end"
        data:
          - type: temp
            measured_data: 21.5
          
  
  
      
        
